['Farming','Animation','Graphic Design','Museums and Institutions','Music','Building Materials',
'Architecture & Planning','Commercial Real Estate','Real Estate',
'Mechanical or Industrial Engineering','Glass, Ceramics & Concrete','Industrial Automation',
'Management Consulting','Market Research','Public Relations and Communications',
'Staffing and Recruiting','Professional Training & Coaching','Human Resources','Import and Export',
'Business Supplies and Equipment','Marketing and Advertising','Program Development',
'Security and Investigations','Logistics and Supply Chain','Primary/Secondary Education',
'Higher Education','Education Management','Research','E-Learning','Banking','Insurance',
'Financial Services','Investment Banking','Investment Management','Capital Markets',
'Venture Capital & Private Equity','Cosmetics','Apparel & Fashion','Supermarkets',
'Luxury Goods & Jewelry','Consumer Electronics','Consumer Goods','Furniture','Retail',
'Electrical/Electronic Manufacturing','Packaging and Containers','Sporting Goods','Military',
'Government Administration','Executive Office','Biotechnology','Law Enforcement',
'Aviation & Aerospace','Renewables & Environment','Nanotechnology','Political Organization',
'Think Tanks','International Trade and Development','Defense & Space','Telecommunications',
'Hospital & Health Care','Health, Wellness and Fitness','Pharmaceuticals','Automotive',
'Chemicals','Machinery','Mining & Metals','Oil & Energy','Shipbuilding','Utilities','Textiles',
'Paper & Forest Products','Railroad Manufacture','Airlines/Aviation','Online Media',
'Entertainment','Newspapers','Publishing','Computer Games','Media Production',
'Information Services','Non-Profit Organization Management','Fund-Raising','Philanthropy',
'Environmental Services','Civic & Social Organization','Consumer Services','Gambling & Casinos',
'Food & Beverages','Package/Freight Delivery','Computer Software','Internet','Semiconductors',
'Information Technology and Services','Computer & Network Security','Wireless',
'Transportation/Trucking/Railroad','Warehousing','Maritime']